//
//  source generated by 'OpenGUI sourcer'
//
 
#include <fastgl/fastgl.h>
 
fgl::FGWindow *TabPages_examplePtr;
static int tmp_str;
static char tmp[4];
static int tmp1;
static int tmp2;
static int tmp3;
static int tmp4;


/*
  This procedure handle all events generated by system and user input
  for all posible events see OpenGUI docs. I you don't want parse any
  events, you can remove this proc, and reference on it from Window CTOR
*/
static void TabPages_exampleProc(fgl::FGEvent *p)
{
    int xWnd = p->GetX();
    int yWnd = p->GetY();
    
    switch(p->GetType()) 
    {
        case fgl::INITEVENT:
            p->wnd->AddPushButton(40, 152, 64, 21, "one", 0, 0);
            p->wnd->AddPushButton(344, 152, 64, 21, "two", 0, 0);
            p->wnd->AddTabPage("first");
            p->wnd->AddEditBox(32, 40, 64, 40, "input1", 0, &tmp_str, 0);
            p->wnd->AddEditBox(3, 304, 128, 64, 40, "string input", 0, tmp, 0);
            p->wnd->AddTabPage("second");
            p->wnd->AddCheckButton(48, 48, "check button", 0, &tmp1, 0);
            p->wnd->AddPointButton(264, 64, "button group", 0, &tmp2, 0);
            p->wnd->AddPointButton(264, 88, "button group", 0, &tmp3, 0);
            p->wnd->AddPointButton(264, 112, "button group", 0, &tmp4, 0);
            p->wnd->AddTabPage("third");
            p->wnd->SetTabPage("first");
            break;
    }
}
 
 
int main(int argc, char **argv)
{
    fgl::FGApp MyApp(fgl::G800x600, argc, argv, fgl::CBLACK, fgl::APP_ENABLEALTX+fgl::APP_CFG);
    TabPages_examplePtr = new fgl::FGWindow(&TabPages_examplePtr, 200, 304, 466, 232, "TabPages example", TabPages_exampleProc,
         fgl::CBLACK, fgl::CWHITED, fgl::WFRAMED|fgl::WTITLED|fgl::WCLICKABLE|fgl::WNOTEBOOK);
    MyApp.Run();
    if (TabPages_examplePtr) delete TabPages_examplePtr;
    return 0;
}
