//
//	source generated by 'OpenGUI sourcer'
//

#include <fastgl/fastgl.h>
#include <fastgl/widgets.h>

fgl::FGWindow *Example_for_FGUpDown_classPtr;
static int var1;
static double var2;


static void Example_for_FGUpDown_classProc(fgl::FGEvent *p)
{
	static fgl::FGUpDown *ud1, *ud2;
	fgl::FGEditBox *eb;
	switch(p->GetType()) 
	{
		case fgl::INITEVENT:
			eb = p->wnd->AddEditBox(112, 32, 64, 64, "integer", 0, &var1, 0, -1000, 1000);
			ud1 = new fgl::FGUpDown(eb, 100);
			eb = p->wnd->AddEditBox(112, 80, 64, 64, "float", 0, &var2, 0, -10.000000, 10.000000);
			ud2 = new fgl::FGUpDown(eb, .2);
			break;
		case fgl::TERMINATEEVENT:
			delete ud1;
			delete ud2;
			fgl::FGApp::AppDone();
			break;
	}
}

int main(int argc, char **argv)
{
	fgl::FGApp MyApp(fgl::G800x600, argc, argv, fgl::CBLACK, fgl::APP_ENABLEALTX + fgl::APP_CFG);
	Example_for_FGUpDown_classPtr = new fgl::FGWindow(&Example_for_FGUpDown_classPtr, 256, 424, 304, 182, "Example for FGUpDown class", Example_for_FGUpDown_classProc,
		 fgl::CBLACK, fgl::CWHITED, fgl::WFRAMED|fgl::WTITLED|fgl::WNOPICTO|fgl::WCENTRED);
	MyApp.Run();
	if (Example_for_FGUpDown_classPtr) delete Example_for_FGUpDown_classPtr;
	return 0;
}
