//
//	source generated by 'FastGL sourcer'
//

#include <fastgl/fastgl.h>
#include <fastgl/widgets.h>


int main(int argc, char **argv)
{
	fgl::FGApp MyApp(4, argc, argv, fgl::CBLACK, fgl::APP_ENABLEALTX+fgl::APP_CFG+fgl::APP_WINDOWDATABASE);
	fgl::FGTextEditor *ed;
	
	if (argc==2) 
		ed = new fgl::FGTextEditor(&ed, argv[1]);
	else 
		ed = new fgl::FGTextEditor(&ed, "Untitled");

	MyApp.Run();

	delete ed;
	return 0;
}

